MSSQL_SERVER=
MSSQL_PORT=
MSSQL_DATABASE=
MSSQL_UID=
MSSQL_PWD=

ESPUTNIK_EMAIL=
ESPUTNIK_PASSWORD=
ESPUTNIK_GROUP_CLIENT_INFO=
ESPUTNIK_FIELD_PHONE=
ESPUTNIK_FIELD_CREATED_AT=
ESPUTNIK_FIELD_BIRTH_DATE=
ESPUTNIK_FIELD_SEX=
ESPUTNIK_FIELD_FIRST_CALL=
ESPUTNIK_FIELD_LAST_CALL=
